spring:
  datasource: #数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mywork_db?useSSL=false
    username: root
    password: lidaxin
    type: com.zaxxer.hikari.HikariDataSource #连接池
    hikari:
      maximum-pool-size: 100 #连接池最大连接数
      connection-timeout: 60000 #超时时间
      idle-timeout: 30000 #最大空闲时间
      minimum-idle: 10 #连接池最小空闲连接数
      auto-commit: true #自动提交
server:
  tomcat:
    max-threads: 200